version: '2'
services:
  database:
    image: mongo
    container_name: app_mongo
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - ./docker/data:/data/db
    command: --storageEngine wiredTiger
  database_admin:
    image: mongo-express:latest
    container_name: mongo_admin
    links:
      - database:mongo
    ports:
      - 8081:8081
  backend-api:
    image: clem/backend-api:latest
    container_name: backend_api
    hostname: backend-api
    links:
      - database:mongo
    ports:
      - 8082:8080
      - 5005:5005
    volumes:
      - ./data:/data
    working_dir: /usr/src/app
    command: npm start
  nginx-front:
    image: clem/nginx-front:latest
    ports:
      - "80:80"
